# dist: trusty
dist: xenial

language: c

perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.8"

install:
  - sudo apt-get update || true
  - sudo apt-get install autopoint libdbi-dev libtool-bin tcl-dev lua5.1 liblua5.1-0-dev valgrind dc python-pip python-setuptools libpango1.0-dev ghostscript
  - sudo pip install cpp-coveralls

before_script:
  - ./bootstrap

script:
  - ./configure --prefix=/opt/rrdtool-master --disable-ruby
  # - make CFLAGS+="-g -O0 -fprofile-arcs -ftest-coverage" LDFLAGS+="-fprofile-arcs --coverage"
  - make
  - make check
  - make check TESTS_STYLE="rrdcached-tcp"
  - make check TESTS_STYLE="rrdcached-unix"
  # - make check TESTS_STYLE="valgrind-logfile"
  # Disable the following, failing tests: rpn1 rpn2 xport1
  # These tests are failing on Travis CI (currently Ubuntu xenial, 16.04LTS), when using valgrind-logfile
  - make check TESTS_STYLE="valgrind-logfile" TESTS="modify1 modify2 modify3 modify4 modify5 tune1 tune2 graph1 rrdcreate dump-restore create-with-source-1 create-with-source-2 create-with-source-3 create-with-source-4 create-with-source-and-mapping-1 create-from-template-1 dcounter1 vformatter1 list1 pdp-calc1"
  - podchecker doc/*.pod
  - sudo make install
  - cd bindings/perl-shared && make test
  - cd ../python && sudo chown -R travis rrdtool.egg-info && python setup.py test
  - /opt/rrdtool-master/bin/rrdtool
  - /opt/rrdtool-master/share/rrdtool/examples/4charts.pl
  - cd ../..
  - make dist
  - tar xf rrdtool-`cat VERSION`.tar.gz
  - cd rrdtool-`cat VERSION`
  - ./configure
  - sudo make install
  - cd /opt/rrdtool-`cat VERSION`
  - ./bin/rrdtool

# after_success:
#  - ( cd src ; find -name '*.c' | xargs -n 1 gcov -a .libs ; find -name '*.c' | xargs -n 1 )
#  - coveralls --no-gcov --encoding latin1 --exclude tests --exclude bindings
