/* Automatic generated by cmake */

#define _freetds_config_h_
/* Define to 1 if you have the <arpa/inet.h> header file. */
/* #undef HAVE_ARPA_INET_H */

/* Define to 1 if you have the <com_err.h> header file. */
/* #undef HAVE_COM_ERR_H */

/* Define to 1 if you have the <dirent.h> header file. */
#define HAVE_DIRENT_H 1

/* Define to 1 if you have the <errno.h> header file. */
#define HAVE_ERRNO_H 1

/* Define to 1 if you have the <getopt.h> header file. */
#define HAVE_GETOPT_H 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <langinfo.h> header file. */
/* #undef HAVE_LANGINFO_H */

/* Define to 1 if you have the <libgen.h> header file. */
#define HAVE_LIBGEN_H 1

/* Define to 1 if you have the <limits.h> header file. */
#define HAVE_LIMITS_H 1

/* Define to 1 if you have the <locale.h> header file. */
#define HAVE_LOCALE_H 1

/* Define to 1 if you have the <malloc.h> header file. */
#define HAVE_MALLOC_H 1

/* Define to 1 if you have the <netdb.h> header file. */
/* #undef HAVE_NETDB_H */

/* Define to 1 if you have the <netinet/in.h> header file. */
/* #undef HAVE_NETINET_IN_H */

/* Define to 1 if you have the <netinet/tcp.h> header file. */
/* #undef HAVE_NETINET_TCP_H */

/* Define to 1 if you have the <paths.h> header file. */
/* #undef HAVE_PATHS_H */

/* Define to 1 if you have the <poll.h> header file. */
/* #undef HAVE_POLL_H */

/* Define to 1 if you have the <roken.h> header file. */
/* #undef HAVE_ROKEN_H */

/* Define to 1 if you have the <signal.h> header file. */
#define HAVE_SIGNAL_H 1

/* Define to 1 if you have the <sql.h> header file. */
#define HAVE_SQL_H 1

/* Define to 1 if you have the <sqlext.h> header file. */
#define HAVE_SQLEXT_H 1

/* Define to 1 if you have the <stddef.h> header file. */
#define HAVE_STDDEF_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <sys/eventfd.h> header file. */
/* #undef HAVE_SYS_EVENTFD_H */

/* Define to 1 if you have the <sys/ioctl.h> header file. */
/* #undef HAVE_SYS_IOCTL_H */

/* Define to 1 if you have the <sys/param.h> header file. */
#define HAVE_SYS_PARAM_H 1

/* Define to 1 if you have the <sys/resource.h> header file. */
/* #undef HAVE_SYS_RESOURCE_H */

/* Define to 1 if you have the <sys/select.h> header file. */
/* #undef HAVE_SYS_SELECT_H */

/* Define to 1 if you have the <sys/socket.h> header file. */
/* #undef HAVE_SYS_SOCKET_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/time.h> header file. */
#define HAVE_SYS_TIME_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <sys/wait.h> header file. */
/* #undef HAVE_SYS_WAIT_H */

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* Define to 1 if you have the <fcntl.h> header file. */
#define HAVE_FCNTL_H 1

/* Define to 1 if you have the <wchar.h> header file. */
#define HAVE_WCHAR_H 1

/* Define to 1 if you have the <windows.h> header file. */
#define HAVE_WINDOWS_H 1

#define SIZEOF_CHAR 1

#define SIZEOF_DOUBLE 8

#define SIZEOF_FLOAT 4

#define SIZEOF_INT 4

#define SIZEOF_SHORT 2

#define SIZEOF_LONG 4

#define SIZEOF_LONG_DOUBLE 16

#define SIZEOF_LONG_LONG 8

#define SIZEOF_SQLWCHAR 2

#define SIZEOF_VOID_P 8

#define SIZEOF_WCHAR_T 2

#define SIZEOF___INT64 8

#define SIZEOF_SQLLEN 8

#define SIZEOF_SQLROWOFFSET 8

#define SIZEOF_SQLROWSETSIZE 8

#define SIZEOF_SQLSETPOSIROW 8

/* Define to 1 if you have type <SQLLEN>. */
#define HAVE_SQLLEN 1

/* Define to 1 if you have type <SQLROWOFFSET>. */
#define HAVE_SQLROWOFFSET 1

/* Define to 1 if you have type <SQLROWSETSIZE>. */
#define HAVE_SQLROWSETSIZE 1

/* Define to 1 if you have type <SQLSETPOSIROW>. */
#define HAVE_SQLSETPOSIROW 1

/* Define to 1 if last argument of SQLColAttribute it's SQLLEN * */
#define TDS_SQLCOLATTRIBUTE_SQLLEN 1

/* Define to 1 if SQLParamOptions accept SQLULEN as arguments */
#define TDS_SQLPARAMOPTIONS_SQLLEN 1

/* Define to 1 if you have function <asprintf>. */
#define HAVE_ASPRINTF 1

/* Define to 1 if you have function <vasprintf>. */
#define HAVE_VASPRINTF 1

/* Define to 1 if you have function <strtok_r>. */
#define HAVE_STRTOK_R 1

/* Define to 1 if you have function <strtok_s>. */
#define HAVE_STRTOK_S 1

/* Define to 1 if you have function <readpassphrase>. */
/* #undef HAVE_READPASSPHRASE */

/* Define to 1 if you have function <strlcpy>. */
/* #undef HAVE_STRLCPY */

/* Define to 1 if you have function <strlcat>. */
/* #undef HAVE_STRLCAT */

/* Define to 1 if you have function <basename>. */
#define HAVE_BASENAME 1

/* Define to 1 if you have function <getopt>. */
#define HAVE_GETOPT 1

/* Define to 1 if you have function <strsep>. */
/* #undef HAVE_STRSEP */

/* Define to 1 if you have function <vsnprintf>. */
#define HAVE_VSNPRINTF 1

/* Define to 1 if you have function <_vsnprintf>. */
#define HAVE__VSNPRINTF 1

/* Define to 1 if you have function <snprintf>. */
#define HAVE_SNPRINTF 1

/* Define to 1 if you have function <_snprintf>. */
#define HAVE__SNPRINTF 1

/* Define to 1 if you have function <_vscprintf>. */
#define HAVE__VSCPRINTF 1

/* Define to 1 if you have function <gettimeofday>. */
#define HAVE_GETTIMEOFDAY 1

/* Define to 1 if you have function <nl_langinfo>. */
/* #undef HAVE_NL_LANGINFO */

/* Define to 1 if you have function <locale_charset>. */
/* #undef HAVE_LOCALE_CHARSET */

/* Define to 1 if you have function <setenv>. */
/* #undef HAVE_SETENV */

/* Define to 1 if you have function <putenv>. */
#define HAVE_PUTENV 1

/* Define to 1 if you have function <getuid>. */
/* #undef HAVE_GETUID */

/* Define to 1 if you have function <getpwuid>. */
/* #undef HAVE_GETPWUID */

/* Define to 1 if you have function <getpwuid_r>. */
/* #undef HAVE_GETPWUID_R */

/* Define to 1 if you have function <fstat>. */
#define HAVE_FSTAT 1

/* Define to 1 if you have function <alarm>. */
#define HAVE_ALARM 1

/* Define to 1 if you have function <fork>. */
/* #undef HAVE_FORK */

/* Define to 1 if you have function <gethrtime>. */
/* #undef HAVE_GETHRTIME */

/* Define to 1 if you have function <localtime_r>. */
/* #undef HAVE_LOCALTIME_R */

/* Define to 1 if you have function <setitimer>. */
/* #undef HAVE_SETITIMER */

/* Define to 1 if you have function <_fseeki64>. */
#define HAVE__FSEEKI64 1

/* Define to 1 if you have function <_ftelli64>. */
#define HAVE__FTELLI64 1

/* Define to 1 if you have function <setrlimit>. */
/* #undef HAVE_SETRLIMIT */

/* Define to 1 if you have function <inet_ntoa_r>. */
/* #undef HAVE_INET_NTOA_R */

/* Define to 1 if you have function <getipnodebyaddr>. */
/* #undef HAVE_GETIPNODEBYADDR */

/* Define to 1 if you have function <getipnodebyname>. */
/* #undef HAVE_GETIPNODEBYNAME */

/* Define to 1 if you have function <getaddrinfo>. */
#define HAVE_GETADDRINFO 1

/* Define to 1 if you have function <inet_ntop>. */
/* #undef HAVE_INET_NTOP */

/* Define to 1 if you have function <gethostname>. */
/* #undef HAVE_GETHOSTNAME */

/* Define to 1 if you have function <poll>. */
/* #undef HAVE_POLL */

/* Define to 1 if you have function <socketpair>. */
/* #undef HAVE_SOCKETPAIR */

/* Define to 1 if you have function <clock_gettime>. */
#define HAVE_CLOCK_GETTIME 1

/* Define to 1 if you have function <fseeko>. */
#define HAVE_FSEEKO 1

/* Define to 1 if you have function <pthread_cond_timedwait>. */
#define HAVE_PTHREAD_COND_TIMEDWAIT 1

/* Define to 1 if you have function <pthread_cond_timedwait_relative_np>. */
#define HAVE_PTHREAD_COND_TIMEDWAIT_RELATIVE_NP 1

/* Define to 1 if you have function <pthread_condattr_setclock>. */
#define HAVE_PTHREAD_CONDATTR_SETCLOCK 1

/* Define to 1 if you have function <_lock_file>. */
#define HAVE__LOCK_FILE 1

/* Define to 1 if you have function <_unlock_file>. */
#define HAVE__UNLOCK_FILE 1

/* Define to 1 if you have function <usleep>. */
#define HAVE_USLEEP 1

/* Define to 1 if you have function <nanosleep>. */
#define HAVE_NANOSLEEP 1

/* Define to 1 if you have function <readdir_r>. */
/* #undef HAVE_READDIR_R */

/* Define to 1 if you have function <eventfd>. */
/* #undef HAVE_EVENTFD */

/* Define to 1 if you have function <daemon>. */
/* #undef HAVE_DAEMON */

/* #undef HAVE_STRUCT_TM_TM_ZONE */

/* #undef HAVE_SQLGETPRIVATEPROFILESTRING */

#define ENABLE_ODBC_WIDE 1

/* #undef ENABLE_EXTRA_CHECKS */

/* #undef ENABLE_KRB5 */

#define ENABLE_ODBC_MARS 1

#define VERSION "1.3.dev.20200914"

#define FREETDS_TOPDIR "/Users/christian/export/local/works/doublegsoft.net/guardwatch/03.Development/guardwatch-agent/lib/freetds-1.2.4"

#ifdef _MSC_VER
#  define inline __inline
#  define _CRT_SECURE_NO_WARNINGS 1
#endif

/* Define to 1 if you want to use SSPI for Win32 */
#define HAVE_SSPI 1

/* define to format string used for 64bit integers */
#define TDS_I64_PREFIX "I64"

/* Define to 1 if you have the SQLGetPrivateProfileString function. */
#define HAVE_SQLGETPRIVATEPROFILESTRING 1

#define _GNU_SOURCE 1

