/*
**                                  _________                   _____        ______
** _______ _____  ________ _______________  /___      ________ ___  /___________  /_
** __  __ `/_  / / /_  __ `/__  ___/_  __  / __ | /| / /_  __ `/_  __/_  ___/__  __ \
** _  /_/ / / /_/ / / /_/ / _  /    / /_/ /  __ |/ |/ / / /_/ / / /_  / /__  _  / / /
** _\__, /  \__,_/  \__,_/  /_/     \__,_/   ____/|__/  \__,_/  \__/  \___/  /_/ /_/
** /____/
**
** Copyright (C) 2020 doublegsoft.net
**
** This program is free software: you can redistribute it and/or modify
** it under the terms of the GNU General Public License as published by
** the Free Software Foundation, either version 3 of the License, or
** (at your option) any later version.
**
** This program is distributed in the hope that it will be useful,
** but WITHOUT ANY WARRANTY; without even the implied warranty of
** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
** GNU General Public License for more details.
**
** You should have received a copy of the GNU General Public License
** along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/

#ifndef __GW_APP_H__
#define __GW_APP_H__

#ifdef __cplusplus
extern "C"
{
#endif

#define KEY_SERVER_ADDRESS                  "SERVER.ADDRESS"
#define KEY_SERVER_SNMP_PORT                "SERVER.SNMP.PORT"
#define KEY_SERVER_WEB_PORT                 "SERVER.WEB.PORT"
#define KEY_AGENT_SNMP_PORT                 "AGENT.SNMP.PORT"
#define KEY_AGENT_WEB_PORT                  "AGENT.WEB.PORT"
#define KEY_AGENT_NAME                      "AGENT.NAME"
#define KEY_AGENT_ACKNOWLEDGEMENT_ID        "AGENT.ACKNOWLEDGEMENT.ID"

typedef struct gw_app_settings_s
{
  /*!
  ** the acknowledge id which is generated by backend.
  */
  char acknowledgement_id[1024];

  /*!
  ** the server address.
  */
  char server_address[1024];

  /*!
  ** the server snmp port.
  */
  char server_snmp_port[1024];

  /*!
  ** the server web port.
  */
  char server_web_port[1024];

  /*!
  ** the server web port.
  */
  char server_web_root[1024];

  /*!
  ** the agent name.
  */
  char agent_name[1024];

  /*!
  ** the agent snmp port.
  */
  char agent_snmp_port[1024];

  /*!
  ** the agent web port.
  */
  char agent_web_port[1024];

  /*!
  ** the rrd file path.
  */
  char rrd_file[2048];
}
gw_app_settings_t;

/*!
** initializes the application presettings.
*/
void
gw_app_init(const char* work_directory);

/*!
** starts guardwatch application and starts all working threads.
*/
void
gw_app_start(const char* work_directory, const char* resources_path);

/*!
** stops guardwatch application and terminates all working threads.
*/
void
gw_app_stop(void);

#ifdef __cplusplus
}
#endif

#endif // __GW_APP_H__